authentication/urls.py
from django.urls import path
from .views import userRegistration, userLogin, userLogout

app_name = "authentication"
urlpatterns = [
    path("login/", userLogin.as_view(), name="login"),
    path("logout/", userLogout, name="logout"),
    path("register/", userRegistration.as_view(), name="register"),
]

esdg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("landing.urls")),
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("authentication/", include("authentication.urls")),
    path("leaderboard/", include("leaderboard.urls")),
    path("tutorial/", include("tutorial.urls")),
]

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

#creates a custom sign up form that includes user email.
class UserSignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]

authentication/views.py
from django.views.generic.edit import FormView, HttpResponseRedirect
from .forms import UserSignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import logout
from django.urls import reverse, reverse_lazy


# Create your views here.
# handles the account creation page
class userRegistration(FormView):
    template_name = "authentication/registration.html"
    form_class = UserSignupForm
    success_url = reverse_lazy("authentication:login")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# handles the login page
class userLogin(LoginView):
    template_name = "authentication/login.html"
    form_class = AuthenticationForm
    success_url = reverse_lazy("game")

    def form_valid(self, form):
        return super().form_valid(form)


def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse("landing:landing"))

authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}

<link rel="stylesheet" href = "{% static 'authentication/css/style.css'%}">
{% endblock %}

{% block content %}
<div class="login-form">
    <h2> Log in</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="login-buttons">
        <button type="submit">Login</button>
        <a href="{% url 'authentication:register' %}">
                <button type="button">Create Account</button>
        </a>
        </div>
    </form>
</div>
{% endblock %}

authentication/templates/authentication/logout.html
<p>You have successfully logged out.</p>

authentication/templates/authentication/registration.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}

<link rel="stylesheet" href = "{% static 'authentication/css/style.css'%}">
{% endblock %}


{% block content %}
<div class="login-form">
    <h2>Create New Account</h2>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</div>
{% endblock %}