esdg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("landing.urls")),
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("authentication/", include("authentication.urls")),
    path("leaderboard/", include("leaderboard.urls")),
    path("tutorial/", include("tutorial.urls")),
]

tutorial/urls.py
from django.urls import path
from .views import tutorialTopicList,topicPageDetail

app_name = "tutorial"
urlpatterns = [
    path("topics/",tutorialTopicList.as_view(), name="tutorial_list"),
    path("topics/<int:pk>/",topicPageDetail.as_view(),name="topic_detail")
]

tutorial/models.py
from django.db import models

# Create your models here.
class TutorialTopic(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

tutorial/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import TutorialTopic

# Create your views here.

#view for the list of topics for the user to select
class tutorialTopicList(ListView):
    template_name = "tutorial/topics.html"
    model = TutorialTopic
    context_object_name = "topics"

#view for when you click on a topic
class topicPageDetail(DetailView):
    template_name = "tutorial/topicDetail.html"
    model = TutorialTopic
    context_object_name = "topic"

tutorial/templates/tutorial/topicDetail.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'tutorial/css/topics.css' %}">
{% endblock %}

{% block content %}
<h1>{{ topic.title }}</h1>
 <div>
    {{ topic.description|linebreaks }}
 </div>
 <button onclick="location.href='/tutorial/topics/'">Back</button>
{% endblock %}

tutorial/templates/tutorial/topics.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'tutorial/css/topics.css' %}">
{% endblock %}

{% block content %}
    <h1>Tutorials & Information </h1>
    <p>Here, you can find pages with helpful information about spam emails.</p>
    <ul>
        {% for topic in topics %}
        <li>
            <a href="{% url 'tutorial:topic_detail' topic.pk %}" >{{topic.title}}</a>
        </li>
        {% empty %}
        <p> no topics yet.</p>
        {% endfor %}
    </ul>
    <button onclick="location.href='/game/create/'">Start a new game</button>
{% endblock %}