authentication/urls.py
from django.urls import path
from .views import userRegistration, userLogin, userLogout

app_name = "authentication"
urlpatterns = [
    path("login/", userLogin.as_view(), name="login"),
    path("logout/", userLogout, name="logout"),
    path("register/", userRegistration.as_view(), name="register"),
]

esdg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("landing.urls")),
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("authentication/", include("authentication.urls")),
    path("leaderboard/", include("leaderboard.urls")),
    path("tutorial/", include("tutorial.urls")),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path("create/", views.create_game_view, name="create_game"),
    path("play/<int:game_id>", views.play_game_view, name="play_game"),
    path("play/<int:game_id>/score", views.game_score_view, name="game_score"),
    path(
        "play/<int:game_id>/<int:email_id>/next-question/<int:is_question_correct>",
        views.next_question_view,
        name="next_question",
    ),
    path(
        "<int:game_id>/tutorial/<int:tutorial_id>/score/<int:score_id>/start/",
        views.start_game_view,
        name="start_game",
    ),
    path(
        "<int:game_id>/tutorial/<int:tutorial_id>/score/<int:score_id>/end/",
        views.end_game_view,
        name="end_game",
    ),
    path("<int:game_id>/email/add/", views.add_email_view, name="add_email"),
    path(
        "<int:game_id>/email/<int:email_id>/modify/",
        views.modify_email_view,
        name="modify_email",
    ),
]

landing/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "landing"
urlpatterns = [
    path("", views.landing_view, name="landing"),
    path("recent-games", views.recent_games_view, name="recent_games"),
]

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse

from game.models import Game

# Create your views here.


def landing_view(request):
    return render(request, "landing/landing.html")


@login_required
def recent_games_view(request):
    context = {}

    number_of_games = 10
    users_games = Game.objects.filter(user=request.user).order_by("-start_time")

    context["games"] = users_games[:number_of_games]

    return render(request, "landing/recent-games.html", context)

landing/templates/landing/landing.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'landing/css/landing.css' %}">
{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
    <p>
        Can you spot the spam before it scams?
        Play head-to-head or solo as you dive into a chaotic inbox full of legit messages and shady spam. Trust your gut—or get fooled!
    </p>
    <div class ="button-container">
    <a href="{% url 'authentication:login' %}">
        <button type="button">Log In</button>
    </a>
    <a href="{% url 'landing:recent_games' %}">
        <button type="button">View Recent Games</button>
    </a>
</div>
{% endblock %}

landing/templates/landing/recent-games.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'landing/css/recent.css' %}">
{% endblock %}
{% block content %}
    <h1>Recent Games</h1>
    <div class="recent-list">
    {% for game in games %}
        <li>
            <span class="date-label">Date: </span><span class="date-value">{{ game.start_time|date:"m/d/y, g:ia" }}</span>
            <span class="score-label">Score: </span><span class="score-value">{{ game.score }} points</span>
        </li>
    {% endfor %}
</div>
<div class ="button-container">
    <a href="{% url 'game:create_game' %}">
        <button type="button">Start a New Game</button>
    </a>
</div>
{% endblock %}