esdg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("landing.urls")),
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("authentication/", include("authentication.urls")),
    path("leaderboard/", include("leaderboard.urls")),
    path("tutorial/", include("tutorial.urls")),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path("create/", views.create_game_view, name="create_game"),
    path("play/<int:game_id>", views.play_game_view, name="play_game"),
    path("play/<int:game_id>/score", views.game_score_view, name="game_score"),
    path(
        "play/<int:game_id>/<int:email_id>/next-question/<int:is_question_correct>",
        views.next_question_view,
        name="next_question",
    ),
    path(
        "<int:game_id>/tutorial/<int:tutorial_id>/score/<int:score_id>/start/",
        views.start_game_view,
        name="start_game",
    ),
    path(
        "<int:game_id>/tutorial/<int:tutorial_id>/score/<int:score_id>/end/",
        views.end_game_view,
        name="end_game",
    ),
    path("<int:game_id>/email/add/", views.add_email_view, name="add_email"),
    path(
        "<int:game_id>/email/<int:email_id>/modify/",
        views.modify_email_view,
        name="modify_email",
    ),
]

landing/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "landing"
urlpatterns = [
    path("", views.landing_view, name="landing"),
    path("recent-games", views.recent_games_view, name="recent_games"),
]

leaderboard/urls.py
from django.urls import path
from . import views

app_name = "leaderboard"
urlpatterns = [
    path("", views.leaderboard_view, name="leaderboard_view"),
]

tutorial/urls.py
from django.urls import path
from .views import tutorialTopicList,topicPageDetail

app_name = "tutorial"
urlpatterns = [
    path("topics/",tutorialTopicList.as_view(), name="tutorial_list"),
    path("topics/<int:pk>/",topicPageDetail.as_view(),name="topic_detail")
]

templates/base.html
<!--Base file in which all html code will be extended so we don't have to rewrite repeatable stuff like this-->
<!DOCTYPE html>
{% csrf_token %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Spam Email Detection Game</title>
        <link href="{% static 'css/global.css' %}" rel="stylesheet">
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        <header class="title-bar">
            <div class="logo">
            <a href="{% url 'landing:landing' %}">
                Spam Email Detection Game
            </a>
            </div>
            <nav class="nav-links">
                <a href="{% url 'game:create_game' %}">Play</a>
                <a href="{% url 'tutorial:tutorial_list' %}">Tutorial</a>
                <a href="{% url 'leaderboard:leaderboard_view' %}">Leaderboard</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'authentication:logout' %}">Log Out</a> 
                {% else %}
                    <a href="{% url 'authentication:login' %}">Log In</a> 
                {% endif %}
            </nav>
        </header>
        <!--extended templates go here-->
        <main>
            {% block content %}{% endblock %}
        </main>
    </body>
</html>